### ISSUE TITLE
Test failure ArgumentError:        cannot start from state :processing_events

### ISSUE THREAD

**Issue by olleolleolle** [ianks/octodown#115]
In Ruby 2.7, 1 test case failed:

```
Failures:

  1) Octodown::Renderer::Server with option :port serves in the specified port
     Failure/Error: @listener.start

     ArgumentError:
       cannot start from state :processing_events
     # ./vendor/bundle/ruby/2.7.0/gems/listen-3.7.1/lib/listen/listener.rb:97:in `start'
     # ./lib/octodown/support/services/riposter.rb:18:in `call'
     # ./lib/octodown/renderer/server.rb:110:in `register_listener'
     # ./lib/octodown/renderer/server.rb:27:in `present'
     # ./spec/lib/renderer/server_spec.rb:70:in `block (3 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # ./vendor/bundle/ruby/2.7.0/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
```
